### ISSUE TITLE
Support for shortcut arguments and other variables

### ISSUE THREAD

**Issue by tonyravioli** [MiniDigger/thelounge-plugin-shortcuts#3]
It'd be neat if a shortcut could support positional arguments, including special arguments based on things like what channel the user is in at the time, the user's current nick, etc.

For instance, let's say I want to be able to add an akick shortcut, and the akick has a duration that the user sets when they run the shortcut.

Setting an akick manually with a 20 minute duration looks like this:
`/msg chanserv akick #thelounge add foobar !T 20`

What if I wanted to do this instead?
`/akick foobar 20`

Maybe the shortcut addition could look something like:
`/shortcut add akick {0} {1} /msg chanserv akick {currentChannel} add {0} !T {1}`
Where:

- `{currentChannel}` is a special string that changes depending on what channel the user sends the command in
- `{0}` and `{1}` are arguments that are passed into the shortcut by the user when they use the shortcut.

This may be beyond the scope of this project.

**Comment by MiniDigger** [comment]
sorry it look so long, but its implemented now. 

deploying a new version later today.
