### ISSUE TITLE
shortcut arguments broken

### ISSUE THREAD

**Issue by Jay2k1** [MiniDigger/thelounge-plugin-shortcuts#5]
one of your examples is aliasing /j to /join, but it does not work. I think the reason is that shortcut arguments (accepted in line 71) are not being passed in line 81: 

https://github.com/MiniDigger/thelounge-plugin-shortcuts/blob/0585bece88723bb5e310c9e1e16fefa91b0f1b56/index.js#L77-L81

**Comment by MiniDigger** [comment]
this actually never was a feature, so its was not a bug 📦 
anyways, its a feature now, deploying later today
