### ISSUE TITLE
does not install

### ISSUE THREAD

**Issue by ahopelesshadow** [MiniDigger/thelounge-plugin-shortcuts#50]
I see the master branch is quite out of date, but most of the PRs for the dependencies can be automerged, but i dont show this even on npm to install anymore, can someone provide a quick how to and how to install this to thelounge via git?  I cloned it with updated dependencies, but get a 'does not have The Lounge metadata' error

**Comment by MiniDigger** [comment]
![https://i.imgur.com/aW60DVT.png](https://i.imgur.com/aW60DVT.png)
I cant see to reproduce this
what command did you ran where and what was the output?

**Comment by ahopelesshadow** [comment]
So part of that was my fault, i think i still have access to the server i was trying on, but i realized the version of the lounge i was trying to install it from was pulled from git not a deb install, i think it may have had to do with that, but im not 100% sure.

**Comment by MiniDigger** [comment]
ill close this then, if you run into this again, feel free to come back, ill promise to react faster next time...
